language: rust
sudo: required

after_success:
  - curl https://stainless-steel.github.io/travis/after_success.sh | bash

env:
  global:
    secure: Q7fYUAkFtCS4tfQwvbchAsdKl1bDasico1XKIYHWFJfPlXeUMUkH95GjWf3pjCvGShfav7mWSbS4SpZrpZC4JFwo254oZQfJ4G1OC2U6LzVKNxU9NYJYS4vrs8sgyp90qQUIdAqQrtZlAxnolPDgPKVD83uC0+er29PftBYVj6RjDdG4JaMV/DqBsBP/SIY/mR/vpvQgUZlFnFnyhUDQWMrqzleLTcUpL9t1c3lnaWiV+QPs7tq4lGe8OXbqKT25Uqm6Ry2Z63tqj4tRUmYSol60leKESaYQ73bdltT6Q2A9VWBZKpZ6Hz4ikzNxA5eAyr3LpBu+ySzW587v3ORYB4jCyVFHvAESlnfiYcjRhRqMTFnUjIqt74yj+LOfsRg5SjGQNb7WJw0JHTIJvMwMLahVDSnLT8KJ2KP52MGXxVoRnlRnTymqA50KGa0wlCgkmyu5xBtq58/hGrE7r2CTviMJF1m38Hux1Ka5ZKFYBldC8Esvx399hoH2OE1sejwSvgJRApZO97sFyUx9godJXjxi42Bxl1xR1YQ54yyVarLN/HHqlKXT77N4CHKp2qWwXmOLnltbRmRbF6AO/Mj+det3ocOqShrJlX41sKlEdrMlW+oP5rXqqVT8RMs7Tjaho8pMKbqCKBwiv+gCD5jCmoQgbzbSj+zefXKRfzrNMP8=

notifications:
  email: false
